// eslint-disable-next-line import/prefer-default-export
export const FETCH_MOVIES_REQUESTED = 'FETCH_MOVIES_REQUESTED';
export const FETCH_MOVIES_RECEIVED = 'FETCH_MOVIES_RECEIVED';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export const FETCH_SEARCH_REQUESTED = 'FETCH_SEARCH_REQUESTED';
export const FETCH_SEARCH_RECEIVED = 'FETCH_SEARCH_RECEIVED';
export const FETCH_SEARCH_ERROR = 'FETCH_SEARCH_ERROR';


export const FETCH_MOVIE_DETAILS_REQUESTED = 'FETCH_MOVIE_DETAILS_REQUESTED';
export const FETCH_MOVIE_DETAILS_RECEIVED = 'FETCH_MOVIE_DETAILS_RECEIVED';
export const FETCH_MOVIE_DETAILS_ERROR = 'FETCH_MOVIE_DETAILS_ERROR';


export const SET_SEARCH_KEYWORD = "SET_SEARCH_KEYWORD";

export const SET_CURRENT_TAB =  "SET_CURRENT_TAB";
